rebuilt with bash libs post 1.1.4

diff --git a/bin/mkservice b/bin/mkservice
--- a/bin/mkservice
+++ b/bin/mkservice
@@ -49,7 +49,7 @@
 #
 ###/doc
 
-##bash-libs: autohelp.sh @ d4f2e817-modified
+##bash-libs: autohelp.sh @ 715e710d (after 1.1.4)
 
 ### autohelp:print [ SECTION [FILE] ] Usage:bbuild
 # Write your help as documentation comments in your script
@@ -60,14 +60,14 @@
 #
 # A help comment looks like this:
 #
-#	### <title> Usage:help
-#	#
-#	# <some content>
-#	#
-#	# end with "###/doc" on its own line (whitespaces before
-#	# and after are OK)
-#	#
-#	###/doc
+#    ### <title> Usage:help
+#    #
+#    # <some content>
+#    #
+#    # end with "###/doc" on its own line (whitespaces before
+#    # and after are OK)
+#    #
+#    ###/doc
 #
 # You can set a different help section by specifying a subsection
 #
@@ -88,10 +88,10 @@
 HELPCHAR='#'
 
 function autohelp:print {
-	local SECTION_STRING="${1:-}"; shift || :
-	local TARGETFILE="${1:-}"; shift || :
-	[[ -n "$SECTION_STRING" ]] || SECTION_STRING=help
-	[[ -n "$TARGETFILE" ]] || TARGETFILE="$0"
+    local SECTION_STRING="${1:-}"; shift || :
+    local TARGETFILE="${1:-}"; shift || :
+    [[ -n "$SECTION_STRING" ]] || SECTION_STRING=help
+    [[ -n "$TARGETFILE" ]] || TARGETFILE="$0"
 
         echo -e "\n$(basename "$TARGETFILE")\n===\n"
         local SECSTART='^\s*'"$HELPCHAR$HELPCHAR$HELPCHAR"'\s+(.+?)\s+Usage:'"$SECTION_STRING"'\s*$'
@@ -107,7 +107,7 @@ function autohelp:print {
                         if [[ "$secline" =~ $SECEND ]]; then
                                 insec=false
                         else
-				echo "$secline" | sed -r "s/^\s*$HELPCHAR//g"
+                echo "$secline" | sed -r "s/^\s*$HELPCHAR//g"
                         fi
                 fi
         done < "$TARGETFILE"
@@ -115,7 +115,7 @@ function autohelp:print {
         if [[ "$insec" = true ]]; then
                 echo "WARNING: Non-terminated help block." 1>&2
         fi
-	echo ""
+    echo ""
 }
 
 ### autohelp:paged Usage:bbuild
@@ -124,8 +124,8 @@ function autohelp:print {
 #
 ###/doc
 function autohelp:paged {
-	: ${PAGER=less}
-	autohelp:print "$@" | $PAGER
+    : ${PAGER=less}
+    autohelp:print "$@" | $PAGER
 }
 
 ### autohelp:check Usage:bbuild
@@ -134,34 +134,34 @@ function autohelp:paged {
 #
 # Example use:
 #
-#	#!/bin/bash
+#    #!/bin/bash
 #
-#	### Some help Usage:help
-#	#
-#	# Some help text
-#	#
-#	###/doc
+#    ### Some help Usage:help
+#    #
+#    # Some help text
+#    #
+#    ###/doc
 #
-#	#%include autohelp.sh
+#    #%include autohelp.sh
 #
-#	main() {
-#		autohelp:check "$@"
+#    main() {
+#        autohelp:check "$@"
 #
-#		# now add your code
-#	}
+#        # now add your code
+#    }
 #
-#	main "$@"
+#    main "$@"
 #
 ###/doc
 autohelp:check() {
-	if [[ "$*" =~ --help ]]; then
-		cols="$(tput cols)"
-		autohelp:print | fold -w "$cols" -s || autohelp:print
-		exit 0
-	fi
+    if [[ "$*" =~ --help ]]; then
+        cols="$(tput cols)"
+        autohelp:print | fold -w "$cols" -s || autohelp:print
+        exit 0
+    fi
 }
 
-##bash-libs: out.sh @ d4f2e817-modified
+##bash-libs: out.sh @ 715e710d (after 1.1.4)
 
 
 ### Console output handlers Usage:bbuild
@@ -170,71 +170,32 @@ autohelp:check() {
 #
 ###/doc
 
-### Environment Variables Usage:bbuild
-#
-# MODE_DEBUG : set to 'true' to enable debugging output
-# MODE_DEBUG_VERBOSE : set to 'true' to enable command echoing
-#
-###/doc
-
-: ${MODE_DEBUG=false}
-: ${MODE_DEBUG_VERBOSE=false}
-
-# Internal
-function out:buffer_initialize {
-	OUTPUT_BUFFER_defer=(:)
-}
-out:buffer_initialize
-
-### out:debug MESSAGE Usage:bbuild
-# print a blue debug message to stderr
-# only prints if MODE_DEBUG is set to "true"
-###/doc
-function out:debug {
-	if [[ "$MODE_DEBUG" = true ]]; then
-		echo "${CBBLU}DEBUG: $CBLU$*$CDEF" 1>&2
-	fi
-}
-
-### out:debug:fork [MARKER] Usage:bbuild
-#
-# Pipe the data coming through stdin to stdout
-#
-# If debug mode is on, *also* write the same data to stderr, each line preceded by MARKER
-#
-# Insert this debug fork into pipes to see their output
-#
-###/doc
-function out:debug:fork {
-	if [[ "$MODE_DEBUG" = true ]]; then
-		local MARKER="${1:-DEBUG: }"; shift || :
-
-		cat - | sed -r "s/^/$MARKER/" | tee -a /dev/stderr
-	else
-		cat -
-	fi
-}
-
 ### out:info MESSAGE Usage:bbuild
 # print a green informational message to stderr
 ###/doc
 function out:info {
-	echo "$CGRN$*$CDEF" 1>&2
+    echo "$CGRN$*$CDEF" 1>&2
 }
 
 ### out:warn MESSAGE Usage:bbuild
 # print a yellow warning message to stderr
 ###/doc
 function out:warn {
-	echo "${CBYEL}WARN: $CYEL$*$CDEF" 1>&2
+    echo "${CBYEL}WARN: $CYEL$*$CDEF" 1>&2
 }
 
 ### out:defer MESSAGE Usage:bbuild
 # Store a message in the output buffer for later use
 ###/doc
 function out:defer {
-	OUTPUT_BUFFER_defer[${#OUTPUT_BUFFER_defer[@]}]="$*"
+    OUTPUT_BUFFER_defer[${#OUTPUT_BUFFER_defer[@]}]="$*"
 }
+
+# Internal
+function out:buffer_initialize {
+    OUTPUT_BUFFER_defer=(:)
+}
+out:buffer_initialize
 
 ### out:flush HANDLER ... Usage:bbuild
 #
@@ -252,15 +213,15 @@ function out:defer {
 #
 ###/doc
 function out:flush {
-	[[ -n "$*" ]] || out:fail "Did not provide a command for buffered output\n\n${OUTPUT_BUFFER_defer[*]}"
+    [[ -n "$*" ]] || out:fail "Did not provide a command for buffered output\n\n${OUTPUT_BUFFER_defer[*]}"
 
-	[[ "${#OUTPUT_BUFFER_defer[@]}" -gt 1 ]] || return 0
+    [[ "${#OUTPUT_BUFFER_defer[@]}" -gt 1 ]] || return 0
 
-	for buffer_line in "${OUTPUT_BUFFER_defer[@]:1}"; do
-		"$@" "$buffer_line"
-	done
+    for buffer_line in "${OUTPUT_BUFFER_defer[@]:1}"; do
+        "$@" "$buffer_line"
+    done
 
-	out:buffer_initialize
+    out:buffer_initialize
 }
 
 ### out:fail [CODE] MESSAGE Usage:bbuild
@@ -269,15 +230,15 @@ function out:flush {
 # if no code is specified, error code 127 is used
 ###/doc
 function out:fail {
-	local ERCODE=127
-	local numpat='^[0-9]+$'
+    local ERCODE=127
+    local numpat='^[0-9]+$'
 
-	if [[ "$1" =~ $numpat ]]; then
-		ERCODE="$1"; shift || :
-	fi
+    if [[ "$1" =~ $numpat ]]; then
+        ERCODE="$1"; shift || :
+    fi
 
-	echo "${CBRED}ERROR FAIL: $CRED$*$CDEF" 1>&2
-	exit $ERCODE
+    echo "${CBRED}ERROR FAIL: $CRED$*$CDEF" 1>&2
+    exit $ERCODE
 }
 
 ### out:error MESSAGE Usage:bbuild
@@ -286,55 +247,9 @@ function out:fail {
 # unlike out:fail, does not cause script exit
 ###/doc
 function out:error {
-	echo "${CBRED}ERROR: ${CRED}$*$CDEF" 1>&2
+    echo "${CBRED}ERROR: ${CRED}$*$CDEF" 1>&2
 }
-
-### out:dump Usage:bbuild
-#
-# Dump stdin contents to console stderr. Requires debug mode.
-#
-# Example
-#
-# 	action_command 2>&1 | out:dump
-#
-###/doc
-
-function out:dump {
-	echo -n "${CBPUR}$*" 1>&2
-	echo -n "$CPUR" 1>&2
-	cat - 1>&2
-	echo -n "$CDEF" 1>&2
-}
-
-### out:break MESSAGE Usage:bbuild
-#
-# Add break points to a script
-#
-# Requires MODE_DEBUG set to true
-#
-# When the script runs, the message is printed with a propmt, and execution pauses.
-#
-# Press return to continue execution.
-#
-# Type `exit`, `quit` or `stop` to stop the program. If the breakpoint is in a subshell,
-#  execution from after the subshell will be resumed.
-#
-###/doc
-
-function out:break {
-	[[ "$MODE_DEBUG" = true ]] || return 0
-
-	echo -en "${CRED}BREAKPOINT: $* >$CDEF " >&2
-	read
-	if [[ "$REPLY" =~ quit|exit|stop ]]; then
-		out:fail "ABORT"
-	fi
-}
-
-if [[ "$MODE_DEBUG_VERBOSE" = true ]]; then
-	set -x
-fi
-##bash-libs: colours.sh @ d4f2e817-modified
+##bash-libs: colours.sh @ 715e710d (after 1.1.4)
 
 ### Colours for bash Usage:bbuild
 # A series of colour flags for use in outputs.
@@ -359,31 +274,105 @@ fi
 #
 # Note that highlight and underline must be applied or re-applied after specifying a colour.
 #
+# If the session is detected as being in a pipe, colours will be turned off.
+#   You can override this by calling `colours:check --color=always` at the start of your script
+#
 ###/doc
 
-export CRED=$(echo -e "\033[0;31m")
-export CGRN=$(echo -e "\033[0;32m")
-export CYEL=$(echo -e "\033[0;33m")
-export CBLU=$(echo -e "\033[0;34m")
-export CPUR=$(echo -e "\033[0;35m")
-export CTEA=$(echo -e "\033[0;36m")
+##bash-libs: tty.sh @ 715e710d (after 1.1.4)
 
-export CBRED=$(echo -e "\033[1;31m")
-export CBGRN=$(echo -e "\033[1;32m")
-export CBYEL=$(echo -e "\033[1;33m")
-export CBBLU=$(echo -e "\033[1;34m")
-export CBPUR=$(echo -e "\033[1;35m")
-export CBTEA=$(echo -e "\033[1;36m")
+tty:is_ssh() {
+    [[ -n "$SSH_TTY" ]] || [[ -n "$SSH_CLIENT" ]] || [[ "$SSH_CONNECTION" ]]
+}
 
-export HLRED=$(echo -e "\033[41m")
-export HLGRN=$(echo -e "\033[42m")
-export HLYEL=$(echo -e "\033[43m")
-export HLBLU=$(echo -e "\033[44m")
-export HLPUR=$(echo -e "\033[45m")
-export HLTEA=$(echo -e "\033[46m")
+tty:is_pipe() {
+    [[ ! -t 1 ]]
+}
 
-export CDEF=$(echo -e "\033[0m")
-##bash-libs: askuser.sh @ d4f2e817-modified
+### colours:check ARGS Usage:bbuild
+#
+# Check the args to see if there's a `--color=always` or `--color=never`
+#   and reload the colours appropriately
+#
+###/doc
+colours:check() {
+    if [[ "$*" =~ --color=always ]]; then
+        COLOURS_ON=true
+    elif [[ "$*" =~ --color=never ]]; then
+        COLOURS_ON=false
+    fi
+
+    colours:define
+    return 0
+}
+
+colours:auto() {
+    if tty:is_pipe ; then
+        COLOURS_ON=false
+    else
+        COLOURS_ON=true
+    fi
+
+    colours:define
+    return 0
+}
+
+colours:define() {
+    if [[ "$COLOURS_ON" = false ]]; then
+
+        export CRED=''
+        export CGRN=''
+        export CYEL=''
+        export CBLU=''
+        export CPUR=''
+        export CTEA=''
+
+        export CBRED=''
+        export CBGRN=''
+        export CBYEL=''
+        export CBBLU=''
+        export CBPUR=''
+        export CBTEA=''
+
+        export HLRED=''
+        export HLGRN=''
+        export HLYEL=''
+        export HLBLU=''
+        export HLPUR=''
+        export HLTEA=''
+
+        export CDEF=''
+
+    else
+
+        export CRED=$(echo -e "\033[0;31m")
+        export CGRN=$(echo -e "\033[0;32m")
+        export CYEL=$(echo -e "\033[0;33m")
+        export CBLU=$(echo -e "\033[0;34m")
+        export CPUR=$(echo -e "\033[0;35m")
+        export CTEA=$(echo -e "\033[0;36m")
+
+        export CBRED=$(echo -e "\033[1;31m")
+        export CBGRN=$(echo -e "\033[1;32m")
+        export CBYEL=$(echo -e "\033[1;33m")
+        export CBBLU=$(echo -e "\033[1;34m")
+        export CBPUR=$(echo -e "\033[1;35m")
+        export CBTEA=$(echo -e "\033[1;36m")
+
+        export HLRED=$(echo -e "\033[41m")
+        export HLGRN=$(echo -e "\033[42m")
+        export HLYEL=$(echo -e "\033[43m")
+        export HLBLU=$(echo -e "\033[44m")
+        export HLPUR=$(echo -e "\033[45m")
+        export HLTEA=$(echo -e "\033[46m")
+
+        export CDEF=$(echo -e "\033[0m")
+
+    fi
+}
+
+colours:auto
+##bash-libs: askuser.sh @ 715e710d (after 1.1.4)
 
 ### askuser Usage:bbuild
 # Present the user with questions on stderr
@@ -403,12 +392,12 @@ blankpat='^ *$'
 # returns 1 otherwise
 ###/doc
 function askuser:confirm {
-	read -p "$* [y/N] > " 1>&2
-	if [[ "$REPLY" =~ $yespat ]]; then
-		return 0
-	else
-		return 1
-	fi
+    read -p "$* [y/N] > " 1>&2
+    if [[ "$REPLY" =~ $yespat ]]; then
+        return 0
+    else
+        return 1
+    fi
 }
 
 ### askuser:ask Usage:bbuild
@@ -417,8 +406,8 @@ function askuser:confirm {
 # Echoes out the entered text
 ###/doc
 function askuser:ask {
-	read -p "$* : " 1>&2
-	echo "$REPLY"
+    read -p "$* : " 1>&2
+    echo "$REPLY"
 }
 
 ### askuser:password Usage:bbuild
@@ -427,8 +416,8 @@ function askuser:ask {
 # Echoes out the entered text
 ###/doc
 function askuser:password {
-	read -s -p "$* : " 1>&2
-	echo "$REPLY"
+    read -s -p "$* : " 1>&2
+    echo "$REPLY"
 }
 
 ### askuser:choose_multi Usage:bbuild
@@ -461,30 +450,27 @@ function askuser:password {
 # If the user selects nothing, then function returns 1 and an empty stdout
 ###/doc
 function askuser:choose_multi {
-	local mesg=$1; shift || :
-	local choices=$(echo "$*"|sed -r 's/ *, */\n/g')
-	out:debug "CHOICES: $choices"
+    local mesg=$1; shift || :
+    local choices=$(echo "$*"|sed -r 's/ *, */\n/g')
 
-	out:info "$mesg:" 
-	local choicelist="$(echo -e "$choices"|egrep '^' -n| sed 's/:/: /')"
-	echo "$choicelist" 1>&2
-	
-	local sel=$(askuser:ask "Choice")
-	if [[ "$sel" =~ $blankpat ]]; then
-		return 1
+    out:info "$mesg:" 
+    local choicelist="$(echo -e "$choices"|egrep '^' -n| sed 's/:/: /')"
+    echo "$choicelist" 1>&2
+    
+    local sel=$(askuser:ask "Choice")
+    if [[ "$sel" =~ $blankpat ]]; then
+        return 1
 
-	elif [[ "$sel" =~ $numpat ]] || [[ "$sel" =~ $rangepat ]]; then
-		out:debug "Number choice [$sel]"
-		echo -e "$choices" | sed -n "$sel p"
-	
-	elif [[ "$sel" =~ $listpat ]]; then
-		echo "$choicelist" | egrep "^${sel// /|}:" | sed -r 's/^[0-9]+: //'
+    elif [[ "$sel" =~ $numpat ]] || [[ "$sel" =~ $rangepat ]]; then
+        echo -e "$choices" | sed -n "$sel p"
+    
+    elif [[ "$sel" =~ $listpat ]]; then
+        echo "$choicelist" | egrep "^${sel// /|}:" | sed -r 's/^[0-9]+: //'
 
-	else
-		out:debug "Pattern choice [$sel]"
-		echo -e "$choices"  |egrep "$(echo "$sel"|tr " " '|')"
-	fi
-	return 0
+    else
+        echo -e "$choices"  |egrep "$(echo "$sel"|tr " " '|')"
+    fi
+    return 0
 }
 
 ### askuser:choose Usage:bbuild
@@ -497,21 +483,21 @@ function askuser:choose_multi {
 # If the user chooses one item, that item is echoed to stdout
 ###/doc
 function askuser:choose {
-	local mesg=$1; shift || :
-	while true; do
-		local thechoice="$(askuser:choose_multi "$mesg" "$*")"
-		local lines=$(echo -n "$thechoice" | grep '$' -c)
-		if [[ $lines = 1 ]]; then
-			echo "$thechoice"
-			return 0
-		elif [[ $lines = 0 ]]; then
-			return 1
-		else
-			out:warn "Too many results"
-		fi
-	done
+    local mesg=$1; shift || :
+    while true; do
+        local thechoice="$(askuser:choose_multi "$mesg" "$*")"
+        local lines=$(echo -n "$thechoice" | grep '$' -c)
+        if [[ $lines = 1 ]]; then
+            echo "$thechoice"
+            return 0
+        elif [[ $lines = 0 ]]; then
+            return 1
+        else
+            out:warn "Too many results"
+        fi
+    done
 }
-##bash-libs: varify.sh @ d4f2e817-modified
+##bash-libs: varify.sh @ 715e710d (after 1.1.4)
 
 ### Varify Usage:bbuild
 # Make a string into a valid variable name or file name
@@ -538,7 +524,7 @@ function askuser:choose {
 # * underscore ("_")
 ###/doc
 function varify:var {
-	echo "$*" | sed -r 's/[^a-zA-Z0-9_]/_/g'
+    echo "$*" | sed -r 's/[^a-zA-Z0-9_]/_/g'
 }
 
 ### varify:fil Usage:bbuild
@@ -556,9 +542,9 @@ function varify:var {
 #
 ###/doc
 function varify:fil {
-	echo "$*" | sed -r 's/[^a-zA-Z0-9_.-]/_/g'
+    echo "$*" | sed -r 's/[^a-zA-Z0-9_.-]/_/g'
 }
-##bash-libs: bincheck.sh @ d4f2e817-modified
+##bash-libs: bincheck.sh @ 715e710d (after 1.1.4)
 
 ### bincheck:get COMMANDS ... Usage:bbuild
 #
@@ -579,18 +565,18 @@ function varify:fil {
 ###/doc
 
 bincheck:get() {
-	local BINEXE=
-	for binname in "$@"; do
-		# Some implementations of `which` print error messages
-		# Not useful here.
-		BINEXE=$(which "$binname" 2>/dev/null)
+    local BINEXE=
+    for binname in "$@"; do
+        # Some implementations of `which` print error messages
+        # Not useful here.
+        BINEXE=$(which "$binname" 2>/dev/null)
 
-		if [[ -n "$BINEXE" ]]; then
-			echo "$BINEXE"
-			return 0
-		fi
-	done
-	return 1
+        if [[ -n "$BINEXE" ]]; then
+            echo "$BINEXE"
+            return 0
+        fi
+    done
+    return 1
 }
 
 ### bincheck:has NAMES ... Usage:bbuild
@@ -600,7 +586,7 @@ bincheck:get() {
 ###/doc
 
 bincheck:has() {
-	[[ -n "$(bincheck:get "$@")" ]]
+    [[ -n "$(bincheck:get "$@")" ]]
 }
 
 ### bincheck:path NAME Usage:bbuild
@@ -612,25 +598,25 @@ bincheck:has() {
 ###/doc
 
 bincheck:path() {
-	local binname="$1"; shift || :
+    local binname="$1"; shift || :
 
-	[[ "$binname" =~ / ]] && { 
-		# A relative path cannot be resolved, just check existence
-		[[ -e "$binname" ]] && echo "$binname" || return 1
+    [[ "$binname" =~ / ]] && { 
+        # A relative path cannot be resolved, just check existence
+        [[ -e "$binname" ]] && echo "$binname" || return 1
 
-	} || binname="$(which "$binname" 2>/dev/null)"
+    } || binname="$(which "$binname" 2>/dev/null)"
 
-	# `which` failed
-	[[ -n "$binname" ]] || return 1
+    # `which` failed
+    [[ -n "$binname" ]] || return 1
 
-	[[ -h "$binname" ]] && {
+    [[ -h "$binname" ]] && {
 
-		local pointedname="$(ls -l "$binname"|grep -oP "$binname.+"|sed "s|$binname -> ||")"
-		bincheck:path "$pointedname" ; return "$?"
-	
-	} || echo "$binname"
+        local pointedname="$(ls -l "$binname"|grep -oP "$binname.+"|sed "s|$binname -> ||")"
+        bincheck:path "$pointedname" ; return "$?"
+    
+    } || echo "$binname"
 }
-##bash-libs: runmain.sh @ d4f2e817-modified
+##bash-libs: runmain.sh @ 715e710d (after 1.1.4)
 
 ### runmain SCRIPTNAME FUNCTION [ARGUMENTS ...] Usage:bbuild
 #
@@ -657,15 +643,15 @@ bincheck:path() {
 ###/doc
 
 function runmain {
-	local required_name="$1"; shift || :
-	local funcall="$1"; shift || :
-	local scriptname="$(basename "$0")"
+    local required_name="$1"; shift || :
+    local funcall="$1"; shift || :
+    local scriptname="$(basename "$0")"
 
-	if [[ "$required_name" = "$scriptname" ]]; then
-		"$funcall" "$@"
-	fi
+    if [[ "$required_name" = "$scriptname" ]]; then
+        "$funcall" "$@"
+    fi
 }
-##bash-libs: isroot.sh @ d4f2e817-modified
+##bash-libs: isroot.sh @ 715e710d (after 1.1.4)
 
 
 ### isroot Usage:bbuild
@@ -675,7 +661,7 @@ function runmain {
 ###/doc
 
 function isroot {
-	[[ "$UID" = 0 ]] || isroot:cygwin
+    [[ "$UID" = 0 ]] || isroot:cygwin
 }
 
 ### isroot:cygwin Usage:bbuild
@@ -687,7 +673,7 @@ function isroot {
 ###/doc
 
 function isroot:cygwin {
-	uname -o | grep -i cygwin -q
+    uname -o | grep -i cygwin -q
 }
 
 ### isroot:require MESSAGE Usage:bbuild
@@ -695,7 +681,7 @@ function isroot:cygwin {
 # print message and exit
 ###/doc
 function isroot:require {
-	isroot || out:fail "$*"
+    isroot || out:fail "$*"
 }
 
 S_USER=nobody
